### PR TITLE
Modified Express adapter to support Express 3.x

### PR DESCRIPTION
**Pull request by Akkuma**
This was a really quick change I made on my side to get Express 3 to run with CoffeeCup. I broke compatibility, but it would be trivial to support the old Express 2 system side-by-side with the new Express 3 system.

### CODE REVIEW

**Comment by twilson63** [comment]
Nice!

Just a suggestion.  Would it be better to submit a pull request to https://github.com/visionmedia/consolidate.js with the express 3 pattern instead of creating specific code inside the template engine that binds to specific framework?

It seems to me that most template engines focus on trying to be framework agnostic to allow for browser compatibility and other framework usage.  Thoughts?

**Comment by Akkuma** [comment]
Thinking about it more, what I think would be best is if the adapters are actually broken out into their own project and treated as plugins for CoffeeCup or entirely removed to follow your suggestion. The former might allow more powerful customization than consolidate aims to provide, since the latter is simply for having an abstraction for templates in Express. For instance, I wanted to implement the ability to declare helpers that exist in every template call. I would modify the adapter code even more to look something like this:

``` coffeescript
compiler: (helpers, options) ->
  return (path, data = {}, cb) ->    
    data[k] = v for k, v of options if options
    data.hardcode ?= {}
    data.hardcode[k] = v for k, v of helpers if helpers
```

This functionality would probably be better baked into the template engine itself though. I'd much prefer not having to declare data.optimize and data.cache every time I ask to render a view and it should simply be a "global" setting depending on if I'm running in development or production.

**Comment by twilson63** [comment]
Totally agree!  I am experimenting with the notion of a plug in
capable coffeecup template engine.  And having  good success, removing
some old dependencies like stylus or uglifyjs.

Check it out if your interested in a plug in capable coffeecup.

https://github.com/twilson63/zeke

Thanks

Tom

Sent from my iPhone

On Jun 23, 2012, at 4:11 PM, Gregory Waxman
reply@reply.github.com
wrote:

**Comment by shimaore** [comment]
@twilson63 wrote:

> Would it be better to submit a pull request to https://github.com/visionmedia/consolidate.js 
> with the express 3 pattern instead of creating specific code inside the template engine
> that binds to specific framework?

`consolidate.js` is hopefully a temporary workaround -- it makes sync template engines work async.

As I see it there are two requirements for a template engine to be Express3-compatible:
- it must export an async -rendering function (`__express` aka `renderFile`);
- it should provide an `include` feature at compile time (to replace `partial` in Express 2).

We can address the first requirement pretty easily in coffeecup (#39). The second one needs work in the compiler.

**Pull request closed without merging**
