### PR TITLE
Add Stylus Support

### PR DESCRIPTION
**Pull request by srackham**
Adds Stylus (http://learnboost.github.com/stylus/) support to CoffeeCup. It allows you to put Stylus CSS markup in CoffeeCup source, for example:

```
doctype 5
html ->
  head ->
    stylus '''
      body
        margin: 0
        font: 12px Helvetica, Arial, sans-serif
    '''
```

Added stylus to devDependencies in package.json (stylus is only needed if the stylus feature is used -- not sure though, dependencies or devDependencies?).

Based on code in this CoffeeKup fork:
https://github.com/cmikec/coffeekup/commit/bd50744f9b3783244ae6b2d5a9694022400e37bc

### CODE REVIEW

**Comment by gradus** [comment]
I think it should go in Dependencies not devDependencies.
I really like this idea, though
Am a big fan of Stylus.
Give me a little to review and I should be able to get this merged in pretty quickly.
Wrestling with Issue #9 at the moment and would like to include my solution along w/ this in the next release

https://groups.google.com/group/coffeekup/browse_thread/thread/42f9b7bb260734d8/ba6159e8ae3fddce?pli=1#ba6159e8ae3fddce

**Comment by gradus** [comment]
quite odd, but your tests are failing for me.

```
TypeError: Cannot call method 'render' of undefined
```

of all things.  Clearly cc is defined.  Let me get to the bottom of this.

**Comment by srackham** [comment]
I've moved stylus dependency from devDependencies to dependencies as suggested 
(https://github.com/srackham/coffeecup/commit/0403db74eb15eba90ff2b669514a2a3d695e7d44).

Get back to me if there are any other changes you need and feel free to make any 
changes you like.

Cheers, Stuart

**Comment by gradus** [comment]
lapse of mental capacity for a moment.
forgot to npm install.
tests passed.
pull request merged.
Thanks a lot.

**Comment by gradus** [comment]
Went ahead and published v0.3.9 with stylus support b/c I needed to lock down the coffeescript version to 1.2.0.
1.3.1 breaks the build and I will need to make some changes to have this work correctly.
Thanks again for your efforts.  Great addition!

**Comment by srackham** [comment]
Wow, that was quick!

Not sure if you saw my third commit: "With Stylus in dependencies the Stylus 
require no longer needs to be guarded"
https://github.com/srackham/coffeecup/commit/d28dd2fba6953c52aa849a66f83c3eddfa5cb563

Cheers, Stuart

**Comment by gradus** [comment]
Nope.  Did not see it, but that is a good point.
I will merge it in now and --force another v0.3.9 publish to npm

**Pull request closed without merging**
